<?php

return [
    // companies and subscriptions  (appear for owner only)
    [
        'name' => ['ar' => 'الشركات', 'en' => 'Companies and plans '],
        'slug' => 'companies_and_plans',
        'route' => '',
        'icon' => 'companies_and_plans',
        'permission_name' => 'sidebar_view_companies_and_plans',
        'order' => 5,
        'is_active' => 1,
        'visible_for_owner_only' => 1,
        'children' => [
            [
                'name' => ['ar' => 'الشركات', 'en' => 'Companies'],
                'slug' => 'companies',
                'route' => 'system.tenant.index',
                'icon' => 'companies',
                'permission_name' => 'sidebar_view_company',
                'order' => 1,
                'is_active' => 1,
            ],
            // [
            //     'name' => ['ar' => 'الباقات', 'en' => 'Plans'],
            //     'slug' => 'plans',
            //     'route' => 'system.plans.index',
            //     'icon' => 'plans',
            //     'permission_name' => 'sidebar_view_plan',
            //     'order' => 4,
            //     'is_active' => 1,
            // ],
        ],
    ],
    // my services
    [
        'name' => ['ar' => 'خدماتي', 'en' => 'My Services'],
        'slug' => 'my_services',
        'route' => '',
        'icon' => 'my_services',
        'permission_name' => 'sidebar_view_my_services',
        'order' => 1,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'الملف الشخصي', 'en' => 'Profile'],
                'slug' => 'profile',
                'route' => '',
                'icon' => 'profile',
                'permission_name' => 'sidebar_view_profile',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الملف المالي', 'en' => 'Financial History'],
                'slug' => 'financial_history',
                'route' => '',
                'icon' => 'financial_history',
                'permission_name' => 'sidebar_view_financial_history',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'وثائقي', 'en' => 'My Documents'],
                'slug' => 'my_documents',
                'route' => '',
                'icon' => 'my_documents',
                'permission_name' => 'sidebar_view_my_documents',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'سجل الحضور', 'en' => 'My Attendance'],
                'slug' => 'my_attendance',
                'route' => '',
                'icon' => 'my_attendance',
                'permission_name' => 'sidebar_view_my_attendance',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'مهامي', 'en' => 'My Assignments'],
                'slug' => 'my_assignments',
                'route' => '',
                'icon' => 'my_assignments',
                'permission_name' => 'sidebar_view_my_assignments',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الإجراءات التأدبية', 'en' => 'Disciplinary Actions'],
                'slug' => 'disciplinary_actions',
                'route' => '',
                'icon' => 'disciplinary_actions',
                'permission_name' => 'sidebar_view_disciplinary_actions',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'طلباتي', 'en' => 'My Requests'],
                'slug' => 'my_requests',
                'route' => '',
                'icon' => 'my_requests',
                'permission_name' => 'sidebar_view_my_requests',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييماتي', 'en' => 'My Evaluation'],
                'slug' => 'my_evaluation',
                'route' => '',
                'icon' => 'my_evaluation',
                'permission_name' => 'sidebar_view_my_evaluation',
                'order' => 8,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييماتي', 'en' => 'My Salary'],
                'slug' => 'my_salary',
                'route' => '',
                'icon' => 'my_salary',
                'permission_name' => 'sidebar_view_my_salary',
                'order' => 9,
                'is_active' => 1,
            ],
        ],
    ],
    // employees
    [
        'name' => ['ar' => 'الموظفون', 'en' => 'Employees'],
        'slug' => 'employees',
        'route' => '',
        'icon' => 'employees',
        'permission_name' => 'sidebar_view_employee',
        'order' => 2,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'ادارة الموظفين', 'en' => 'Employees management'],
                'slug' => 'employees_management',
                'route' => 'system.users.index',
                'icon' => 'employees_management',
                'permission_name' => 'sidebar_view_employee',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييم الموظفين', 'en' => 'Employees Evaluation'],
                'slug' => 'employees_evaluation',
                'route' => 'system.employee-evaluation.index',
                'icon' => 'employees_evaluation',
                'permission_name' => 'sidebar_employee_evaluation',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'عهد الموظفين', 'en' => 'Employee Assets'],
                'slug' => 'employee_assets',
                'route' => 'system.employee-assets.index',
                'icon' => 'employee_assets',
                'permission_name' => 'sidebar_employee_assets',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'إدارة التوظيف', 'en' => 'Hiring Management'],
                'slug' => 'hiring_management',
                'route' => 'system.opening-positions.index',
                'icon' => 'hiring_management',
                'permission_name' => 'sidebar_view_hiring_management',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'عقود الموظفين', 'en' => 'Employee Contracts'],
                'slug' => 'employee_contracts',
                'route' => 'system.employee-contracts.index',
                'icon' => 'employee_contracts',
                'permission_name' => 'sidebar_view_employee_contracts',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'المناصب الوظيفية', 'en' => 'Positions'],
                'slug' => 'positions',
                'route' => 'system.position.index',
                'icon' => 'positions',
                'permission_name' => 'sidebar_view_position',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'المسميات الوظيفية', 'en' => 'Job Title'],
                'slug' => 'job_titles',
                'route' => 'system.job-titles.index',
                'icon' => 'job_title',
                'permission_name' => 'sidebar_view_job_title',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'طلبات الموظفين', 'en' => 'Employee Requests'],
                'slug' => 'employee_requests',
                'route' => 'system.employee-requests.index',
                'icon' => 'employee_requests',
                'permission_name' => 'sidebar_view_employee_requests',
                'order' => 8,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'إخلاء طرف موظف', 'en' => 'Exit Clearance'],
                'slug' => 'exit_clearance',
                'route' => 'system.employee-clearances.index',
                'icon' => 'exit_clearance',
                'permission_name' => 'sidebar_view_exit_clearance',
                'order' => 9,
                'is_active' => 1,
            ],
        ],
    ],
    // salary
    [
        'name' => ['ar' => 'الرواتب', 'en' => 'Salary'],
        'slug' => 'salary',
        'route' => '',
        'icon' => 'salary',
        'permission_name' => 'sidebar_view_salary',
        'order' => 3,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            // [
            //     'name' => ['ar' => 'الطلبات المالية', 'en' => 'Financial Request'],
            //     'slug' => 'financial_request',
            //     'route' => '',
            //     'icon' => 'financial_request',
            //     'permission_name' => 'sidebar_view_financial_request',
            //     'order' => 1,
            //     'is_active' => 1,
            // ],
            [
                'name' => ['ar' => 'العمل الاضافي', 'en' => 'Overtime'],
                'slug' => 'overtime',
                'route' => '',
                'icon' => 'overtime',
                'permission_name' => 'sidebar_view_overtime',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الحركات المالية', 'en' => 'Financial Transactions'],
                'slug' => 'financial_transactions',
                'route' => '',
                'icon' => 'financial_transactions',
                'permission_name' => 'sidebar_view_financial_transaction',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تذاكر الطيران', 'en' => 'Airline Tickets'],
                'slug' => 'airline_tickets',
                'route' => '',
                'icon' => 'airline_tickets',
                'permission_name' => 'sidebar_view_airline_tickets',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'رواتب الاجازات', 'en' => 'Leave Salary'],
                'slug' => 'leave_salary',
                'route' => '',
                'icon' => 'leave_salary',
                'permission_name' => 'sidebar_view_leave_salary',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'ادارة الرواتب', 'en' => 'Salary Management'],
                'slug' => 'salary_management',
                'route' => '',
                'icon' => 'salary_management',
                'permission_name' => 'sidebar_view_salary_management',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'ساعات العمل', 'en' => 'Working Hours'],
                'slug' => 'working_hours',
                'route' => '',
                'icon' => 'working_hours',
                'permission_name' => 'sidebar_view_working_hours',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'هيكلة نظام الرواتب', 'en' => 'Salary Structure'],
                'slug' => 'salary_structure',
                'route' => '',
                'icon' => 'salary_structure',
                'permission_name' => 'sidebar_view_salary_structure',
                'order' => 8,
                'is_active' => 1,
            ],
        ],
    ],

    // attendance rule
    [
        'name' => ['ar' => 'الحضور والانصراف', 'en' => 'Attendance'],
        'slug' => 'attendance',
        'route' => '',
        'icon' => 'attendance',
        'permission_name' => 'sidebar_view_attendance',
        'order' => 5,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'تهيئة الحضور والانصراف', 'en' => 'Attendance Setup'],
                'slug' => 'attendance_setup',
                'route' => 'system.attendance-rules.index',
                'icon' => 'attendance_setup',
                'permission_name' => 'sidebar_view_attendance_setup',
                'order' => 1,
                'is_active' => 1,
            ],
        ],
    ],

    // settings
    [
        'name' => ['ar' => 'الاعدادات العامة', 'en' => 'Genaral Settings'],
        'slug' => 'general_settings',
        'route' => '',
        'icon' => 'settings',
        'permission_name' => 'sidebar_view_general_settings',
        'order' => 4,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'الفروع', 'en' => 'Branches'],
                'slug' => 'branches',
                'route' => 'system.branch.index',
                'icon' => 'branches',
                'permission_name' => 'sidebar_view_branch',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الاقسام', 'en' => 'Departments'],
                'slug' => 'departments',
                'route' => 'system.department.index',
                'icon' => 'departments',
                'permission_name' => 'sidebar_view_department',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'اعدادات الشركة', 'en' => 'Company Settings'],
                'slug' => 'company_settings',
                'route' => '',
                'icon' => 'company_settings',
                'permission_name' => 'sidebar_view_company_settings',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'المشرفين', 'en' => 'Supervisors'],
                'slug' => 'supervisors',
                'route' => '',
                'icon' => 'supervisors',
                'permission_name' => 'sidebar_view_supervisor',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'السلف', 'en' => 'Employee Advance'],
                'slug' => 'employee_advances',
                'route' => '',
                'icon' => 'employee_advances',
                'permission_name' => 'sidebar_view_employee_advance',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'انواع عهد الموظفين', 'en' => 'Employee Assets types'],
                'slug' => 'employee_assets_types',
                'route' => 'system.employee-asset-types.index',
                'icon' => 'employee_assets_types',
                'permission_name' => 'sidebar_view_employee_assets_types',
                'order' => 8,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الصلاحيات', 'en' => 'Permissions'],
                'slug' => 'permissions',
                'route' => 'system.role.index',
                'icon' => 'Permissions',
                'permission_name' => 'sidebar_view_permission',
                'order' => 9,
                'is_active' => 1,
            ],
        ],
    ],

    // Leaves
    [
        'name' => ['ar' => 'الاجازات', 'en' => 'Leaves'],
        'slug' => 'leaves',
        'route' => '',
        'icon' => 'leaves',
        'permission_name' => 'sidebar_view_leaves',
        'order' => 4,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'ادارة الاجازات', 'en' => 'Leave Management'],
                'slug' => 'leave_management',
                'route' => 'system.leaves.index',
                'icon' => 'leave_management',
                'permission_name' => 'sidebar_view_leave_management',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الأجازات المرحلة', 'en' => 'Carried forward leaves'],
                'slug' => 'carried_forward_leaves',
                'route' => '',
                'icon' => 'carried_forward_leaves',
                'permission_name' => 'sidebar_view_carried_forward_leaves',
                'order' => 2,
                'is_active' => 1,
            ],

        ],
    ],
    // my current subscriptions
    [
        'name' => ['ar' => 'الاشتراكات', 'en' => 'Subscriptions'],
        'slug' => 'my_current_subscriptions',
        'route' => '',
        'icon' => 'my_current_subscriptions',
        'permission_name' => 'sidebar_view_my_current_subscriptions',
        'order' => 6,
        'is_active' => 1,
        'visible_for_owner_only' => 0,
        'children' => [
            [
                'name' => ['ar' => 'الاشتراك الحالي', 'en' => 'Current Subscription'],
                'slug' => 'my_subscriptions',
                'route' => '',
                'icon' => 'my_current_subscription',
                'permission_name' => 'sidebar_view_my_subscriptions',
                'order' => 1,
                'is_active' => 1,
            ],
        ],
    ],
];
