<?php

return [
    [
        'name' => ['ar' => 'خدماتي', 'en' => 'My Services'],
        'slug' => 'my_services',
        'route' => '/my_services',
        'icon' => 'my_services',
        'permission_name' => 'sidebar_view_my_services',
        'order' => 1,
        'is_active' => 1,
        'children' => [
            [
                'name' => ['ar' => 'الملف الشخصي', 'en' => 'Profile'],
                'slug' => 'profile',
                'route' => '/profile',
                'icon' => 'profile',
                'permission_name' => 'sidebar_view_profile',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الملف المالي', 'en' => 'Financial History'],
                'slug' => 'financial_history',
                'route' => '/financial_history',
                'icon' => 'financial_history',
                'permission_name' => 'sidebar_view_financial_history',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'وثائقي', 'en' => 'My Documents'],
                'slug' => 'my_documents',
                'route' => '/my_documents',
                'icon' => 'my_documents',
                'permission_name' => 'sidebar_view_my_documents',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'سجل الحضور', 'en' => 'My Attendance'],
                'slug' => 'my_attendance',
                'route' => '/my_attendance',
                'icon' => 'my_attendance',
                'permission_name' => 'sidebar_view_my_attendance',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'مهامي', 'en' => 'My Assignments'],
                'slug' => 'my_assignments',
                'route' => '/my_assignments',
                'icon' => 'my_assignments',
                'permission_name' => 'sidebar_view_my_assignments',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الإجراءات التأدبية', 'en' => 'Disciplinary Actions'],
                'slug' => 'disciplinary_actions',
                'route' => '/disciplinary_actions',
                'icon' => 'disciplinary_actions',
                'permission_name' => 'sidebar_view_disciplinary_actions',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'طلباتي', 'en' => 'My Requests'],
                'slug' => 'my_requests',
                'route' => '/my_requests',
                'icon' => 'my_requests',
                'permission_name' => 'sidebar_view_my_requests',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييماتي', 'en' => 'My Evaluation'],
                'slug' => 'my_evaluation',
                'route' => '/my_evaluation',
                'icon' => 'my_evaluation',
                'permission_name' => 'sidebar_view_my_evaluation',
                'order' => 8,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييماتي', 'en' => 'My Salary'],
                'slug' => 'my_salary',
                'route' => '/my_salary',
                'icon' => 'my_salary',
                'permission_name' => 'sidebar_view_my_salary',
                'order' => 9,
                'is_active' => 1,
            ],
        ],
    ],
    [
        'name' => ['ar' => 'الاعدادات العامة', 'en' => 'Genaral Settings'],
        'slug' => 'general_settings',
        'route' => '/general_settings',
        'icon' => 'settings',
        'permission_name' => 'sidebar_view_general_settings',
        'order' => 1,
        'is_active' => 1,
        'children' => [
            [
                'name' => ['ar' => 'الشركات', 'en' => 'Companies'],
                'slug' => 'companies',
                'route' => '/companies',
                'icon' => 'companies',
                'permission_name' => 'sidebar_view_company',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الفروع', 'en' => 'Branches'],
                'slug' => 'branches',
                'route' => '/branches',
                'icon' => 'branches',
                'permission_name' => 'sidebar_view_branch',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الباقات', 'en' => 'Plans'],
                'slug' => 'plans',
                'route' => '/plans',
                'icon' => 'plans',
                'permission_name' => 'sidebar_view_plan',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'اعدادات الشركة', 'en' => 'Company Settings'],
                'slug' => 'company_settings',
                'route' => '/company_settings',
                'icon' => 'company_settings',
                'permission_name' => 'sidebar_view_company_settings',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'المشرفين', 'en' => 'Supervisors'],
                'slug' => 'supervisors',
                'route' => '/supervisors',
                'icon' => 'supervisors',
                'permission_name' => 'sidebar_view_supervisor',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'السلف', 'en' => 'Employee Advance'],
                'slug' => 'employee_advances',
                'route' => '/employee_advances',
                'icon' => 'employee_advances',
                'permission_name' => 'sidebar_view_employee_advance',
                'order' => 6,
                'is_active' => 1,
            ],
        ],
    ],
    [
        'name' => ['ar' => 'الرواتب', 'en' => 'Salary'],
        'slug' => 'salary',
        'route' => '/salary',
        'icon' => 'salary',
        'permission_name' => 'sidebar_view_salary',
        'order' => 2,
        'is_active' => 1,
        'children' => [
            [
                'name' => ['ar' => 'الطلبات المالية', 'en' => 'Financial Request'],
                'slug' => 'financial_request',
                'route' => '/financial_request',
                'icon' => 'financial_request',
                'permission_name' => 'sidebar_view_financial_request',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'العمل الاضافي', 'en' => 'Overtime'],
                'slug' => 'overtime',
                'route' => '/overtime',
                'icon' => 'overtime',
                'permission_name' => 'sidebar_view_overtime',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'الحركات المالية', 'en' => 'Financial Transactions'],
                'slug' => 'financial_transactions',
                'route' => '/financial_transactions',
                'icon' => 'financial_transactions',
                'permission_name' => 'sidebar_view_financial_transaction',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تذاكر الطيران', 'en' => 'Airline Tickets'],
                'slug' => 'airline_tickets',
                'route' => '/airline_tickets',
                'icon' => 'airline_tickets',
                'permission_name' => 'sidebar_view_airline_tickets',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'رواتب الاجازات', 'en' => 'Leave Salary'],
                'slug' => 'leave_salary',
                'route' => '/leave_salary',
                'icon' => 'leave_salary',
                'permission_name' => 'sidebar_view_leave_salary',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'ادارة الرواتب', 'en' => 'Salary Management'],
                'slug' => 'salary_management',
                'route' => '/salary_management',
                'icon' => 'salary_management',
                'permission_name' => 'sidebar_view_salary_management',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'ساعات العمل', 'en' => 'Working Hours'],
                'slug' => 'working_hours',
                'route' => '/working_hours',
                'icon' => 'working_hours',
                'permission_name' => 'sidebar_view_working_hours',
                'order' => 7,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'هيكلة نظام الرواتب', 'en' => 'Salary Structure'],
                'slug' => 'salary_structure',
                'route' => '/salary_structure',
                'icon' => 'salary_structure',
                'permission_name' => 'sidebar_view_salary_structure',
                'order' => 8,
                'is_active' => 1,
            ],
        ],
    ],
    [
        'name' => ['ar' => 'الموظفون', 'en' => 'Employees'],
        'slug' => 'employees',
        'route' => '/employees',
        'icon' => 'employees',
        'permission_name' => 'sidebar_view_employee',
        'order' => 2,
        'is_active' => 1,
        'children' => [
            [
                'name' => ['ar' => 'ادارة الموظفين', 'en' => 'Employees management'],
                'slug' => 'employees_management',
                'route' => '/employees_management',
                'icon' => 'employees_management',
                'permission_name' => 'sidebar_view_employee',
                'order' => 1,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'تقييم الموظفين', 'en' => 'Employees Evaluation'],
                'slug' => 'employees_evaluation',
                'route' => '/employees_evaluation',
                'icon' => 'employees_evaluation',
                'permission_name' => 'sidebar_employee_evaluation',
                'order' => 2,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'عهد الموظفين', 'en' => 'Employee Assets'],
                'slug' => 'employee_assets',
                'route' => '/employee_assets',
                'icon' => 'employee_assets',
                'permission_name' => 'sidebar_employee_assets',
                'order' => 3,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'عقود الموظفين', 'en' => 'Employee Contracts'],
                'slug' => 'employee_contracts',
                'route' => '/employee_contracts',
                'icon' => 'employee_contracts',
                'permission_name' => 'sidebar_view_employee_contracts',
                'order' => 4,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'المناصب الوظيفية', 'en' => 'Positions'],
                'slug' => 'positions',
                'route' => '/positions',
                'icon' => 'positions',
                'permission_name' => 'sidebar_view_position',
                'order' => 5,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'طلبات الموظفين', 'en' => 'Employee Requests'],
                'slug' => 'employee_requests',
                'route' => '/employee_requests',
                'icon' => 'employee_requests',
                'permission_name' => 'sidebar_view_employee_requests',
                'order' => 6,
                'is_active' => 1,
            ],
            [
                'name' => ['ar' => 'إخلاء طرف موظف', 'en' => 'Exit Clearance'],
                'slug' => 'exit_clearance',
                'route' => '/exit_clearance',
                'icon' => 'exit_clearance',
                'permission_name' => 'sidebar_view_exit_clearance',
                'order' => 7,
                'is_active' => 1,
            ],
        ],
    ],
];
